name: inno_chatbot

networks:
  inno_chatbot:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

services:
  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env
    volumes:
      - ${PWD}/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      inno_chatbot:
        ipv4_address: ${OLLAMA_HOST}
    ports:
      - ${OLLAMA_PORT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

  bart:
    image: innodiskorg/ivit-chatbot:model-server-beta
    container_name: bart_server
    restart: always
    volumes:
      - ${PWD}/hf_models:/workspace/hf_models
    networks:
      inno_chatbot:
        ipv4_address: ${BART_HOST}
    ports:
      - ${BART_PORT}
    shm_size: '8g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    command: uvicorn app_bart:app --host 0.0.0.0 --port ${BART_PORT} --workers ${BART_WORKERS}

  doc_embed:
    image: innodiskorg/ivit-chatbot:doc-emb-server-beta
    container_name: doc_embed_server
    restart: always
    env_file:
      - .env
    volumes:
      - ${PWD}/hf_models:/workspace/hf_models
      - ${PWD}/upload_pdf:/workspace/upload_pdf
    networks:
      inno_chatbot:
        ipv4_address: ${DOC_EMBED_HOST}
    ports:
      - ${DOC_EMBED_PORT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    command: uvicorn app:app --host 0.0.0.0 --port ${DOC_EMBED_PORT} --workers ${DOC_EMBED_WORKERS}

  postgres:
    image: ankane/pgvector
    container_name: pgvector
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/postgres/:${PGDATA}
    networks:
      inno_chatbot:
        ipv4_address: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}
    command: "-c max_connections=200 -p ${POSTGRES_PORT}"
    
  core:
    image: innodiskorg/rag:beta-v0.1
    build: ./docker
    container_name: rag_v1
    restart: always
    volumes:
      - ${PWD}:/workspace/
    env_file:
      - .env
    networks:
      inno_chatbot:
        ipv4_address: ${CORE_HOST}
    ports:
      - ${CORE_PORT}:${CORE_PORT}
    depends_on:
      - ollama
      - bart
      - postgres
      - doc_embed
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: uvicorn app:app --host 0.0.0.0 --port ${CORE_PORT} --reload
    ipc: host
    runtime: nvidia

  streamlit:
    image: streamlit-webui
    build: 
      context: ./webui
      dockerfile: docker/Dockerfile
    container_name: streamlit-webui
    restart: always
    env_file:
      - .env
    networks:
      - inno_chatbot
    ports:
      - ${STREAMLIT_PORT}:${STREAMLIT_PORT}
    depends_on:
      - core
